-
  -
    -
      - x: 0.00049325550207868218
        y: -0.533943772315979
        z: -0.0025650793686509132
        qw: -0.00021975437469431918
        qx: -0.047561250760981819
        qy: -0.0019374600776795169
        qz: 0.99856181906851538
      - x: 0.090773724019527435
        y: -0.53393805027008057
        z: 0.010574314743280411
        qw: -0.00021975437469431918
        qx: -0.047561250760981819
        qy: -0.0019374600776795169
        qz: 0.99856181906851538
      - x: 0.18189431726932526
        y: -0.53393614292144775
        z: 0.014998560771346092
        qw: -0.0001062560145424113
        qx: -0.0011122662400516853
        qy: -0.0020205132159694028
        qz: 0.99972949485754814
      - x: 0.27303138375282288
        y: -0.53393793106079102
        z: 0.010911471210420132
        qw: 9.8249932326238999e-06
        qx: 0.044767706920847208
        qy: -0.0014897808968678328
        qz: 0.99874549996904649
      - x: 0.36337661743164062
        y: -0.53394341468811035
        z: -0.0017538924003019929
        qw: 9.5878930269036763e-05
        qx: 0.072548139814483173
        qy: -0.00098489182952713264
        qz: 0.99735999318411173
  -
    -
      - x: 0.36343508958816528
        y: -0.63394343852996826
        z: -0.0018429318442940712
        qw: 8.7379369963428631e-05
        qx: 0.07061916531265193
        qy: -0.00086432431741950385
        qz: 0.9975008096108291
      - x: 0.2730720043182373
        y: -0.6339380145072937
        z: 0.01063349936157465
        qw: 8.5432560253591564e-06
        qx: 0.044321455217834482
        qy: -0.0013016809029599899
        qz: 0.99876528345958704
      - x: 0.1819397509098053
        y: -0.63393634557723999
        z: 0.014635661616921425
        qw: -9.610362285998242e-05
        qx: -0.00024924950679525452
        qy: -0.0017657225337934165
        qz: 0.99970746548105005
      - x: 0.090828657150268555
        y: -0.6339382529258728
        z: 0.010191004723310471
        qw: -0.00019358014127604642
        qx: -0.047034075672062685
        qy: -0.0016948693709513505
        qz: 0.99859473341885296
      - x: 0.00053763488540425897
        y: -0.63394385576248169
        z: -0.0027961959131062031
        qw: -0.00019358014127604642
        qx: -0.047034075672062685
        qy: -0.0016948693709513505
        qz: 0.99859473341885296
  -
    -
      - x: 0.00056924630189314485
        y: -0.73394393920898438
        z: -0.0029609818011522293
        qw: -0.00016096279318757412
        qx: -0.046450631919492696
        qy: -0.0013758569616483726
        qz: 0.99862993045407022
      - x: 0.090873435139656067
        y: -0.73393839597702026
        z: 0.0098641570657491684
        qw: -0.00016096279318757412
        qx: -0.046450631919492696
        qy: -0.0013758569616483726
        qz: 0.99862993045407022
      - x: 0.18197700381278992
        y: -0.73393648862838745
        z: 0.014242528006434441
        qw: -7.8223225609654425e-05
        qx: -0.0014492966195339199
        qy: -0.0014547044759955613
        qz: 0.99974338876030078
      - x: 0.27310192584991455
        y: -0.73393815755844116
        z: 0.010382351465523243
        qw: 8.1625203453747585e-06
        qx: 0.043278859932470708
        qy: -0.0010138934433716962
        qz: 0.99881731766810333
      - x: 0.36348614096641541
        y: -0.73394346237182617
        z: -0.001879208255559206
        qw: 6.5182241065334958e-05
        qx: 0.070230094822581357
        qy: -0.00055760140804537604
        qz: 0.99752653287434145
  -
    -
      - x: 0.36352810263633728
        y: -0.83394348621368408
        z: -0.0018499144352972507
        qw: 3.4083952761487759e-05
        qx: 0.068234719521537174
        qy: -8.2513282856245819e-05
        qz: 0.99766674623291285
      - x: 0.27311939001083374
        y: -0.83393824100494385
        z: 0.010160163044929504
        qw: 8.6921428533035111e-06
        qx: 0.042519145421228928
        qy: -0.0005994888807324914
        qz: 0.99886682535792137
      - x: 0.18200258910655975
        y: -0.83393663167953491
        z: 0.014019723981618881
        qw: -6.0594365681364031e-05
        qx: -0.0010285475911698812
        qy: -0.0010540100385643869
        qz: 0.99972833827350238
      - x: 0.090908445417881012
        y: -0.83393853902816772
        z: 0.0095905205234885216
        qw: -0.00012380669785957079
        qx: -0.045957471982855803
        qy: -0.0010025612431318104
        qz: 0.99866419794166417
      - x: 0.00058835581876337528
        y: -0.83394402265548706
        z: -0.0030608219094574451
        qw: -0.00012380669785957079
        qx: -0.045957471982855803
        qy: -0.0010025612431318104
        qz: 0.99866419794166417
  -
    -
      - x: 0.00059514486929401755
        y: -0.93394404649734497
        z: -0.0030966650228947401
        qw: -7.9258285757943206e-05
        qx: -0.045553855098148688
        qy: -0.00053504854804964754
        qz: 0.99869039378895963
      - x: 0.090928338468074799
        y: -0.93393862247467041
        z: 0.0094244014471769333
        qw: -7.9258285757943206e-05
        qx: -0.045553855098148688
        qy: -0.00053504854804964754
        qz: 0.99869039378895963
      - x: 0.18201765418052673
        y: -0.9339367151260376
        z: 0.013819054700434208
        qw: -3.6662359343914388e-05
        qx: -0.0016370235462053963
        qy: -0.00056249343520469288
        qz: 0.99974613656844735
      - x: 0.27313196659088135
        y: -0.93393832445144653
        z: 0.010062367655336857
        qw: 8.7412618275676308e-06
        qx: 0.041919312781426396
        qy: -0.00010436598539019877
        qz: 0.9988931559110924
      - x: 0.36355909705162048
        y: -0.93394345045089722
        z: -0.0017418696079403162
        qw: 5.3842027725355624e-06
        qx: 0.067961086313658992
        qy: 0.00036809929046757934
        qz: 0.99768305281091396
  -
    -
      - x: 0.36357876658439636
        y: -1.0339434146881104
        z: -0.0015513536054641008
        qw: -1.8719696416216543e-05
        qx: 0.066280365060599158
        qy: 0.0007504394696187859
        qz: 0.99779785716550129
      - x: 0.27313262224197388
        y: -1.0339384078979492
        z: 0.010075381025671959
        qw: 9.2635335979522422e-06
        qx: 0.041228660041582259
        qy: 0.00035510155254447613
        qz: 0.99893334651161614
      - x: 0.18201784789562225
        y: -1.0339367389678955
        z: 0.01380540058016777
        qw: -1.217162103129096e-05
        qx: -0.0011670444738023642
        qy: -3.5668217082865123e-05
        qz: 0.99972586651977513
      - x: 0.090935677289962769
        y: -1.0339386463165283
        z: 0.0093289641663432121
        qw: -3.6835273560263393e-05
        qx: -0.045313456562580796
        qy: -8.0245698511132617e-05
        qz: 0.99871128424385291
      - x: 0.00059013190912082791
        y: -1.0339440107345581
        z: -0.003071177750825882
        qw: -3.6835273560263393e-05
        qx: -0.045313456562580796
        qy: -8.0245698511132617e-05
        qz: 0.99871128424385291
  -
    -
      - x: 0.00057424616534262896
        y: -1.133944034576416
        z: -0.0029892188031226397
        qw: 5.5354331245075149e-06
        qx: -0.04543578374594185
        qy: 0.00038779569090564706
        qz: 0.99871705548609291
      - x: 0.090927280485630035
        y: -1.1339386701583862
        z: 0.0093416571617126465
        qw: 5.5354331245075149e-06
        qx: -0.04543578374594185
        qy: 0.00038779569090564706
        qz: 0.99871705548609291
      - x: 0.18200474977493286
        y: -1.1339367628097534
        z: 0.013870278373360634
        qw: 1.4740630885853034e-05
        qx: -0.00084766110371976768
        qy: 0.00051596608109350569
        qz: 0.99971168889166606
      - x: 0.27312752604484558
        y: -1.1339379549026489
        z: 0.010258273221552372
        qw: 6.8757700426203685e-06
        qx: 0.039991071259939656
        qy: 0.00087783063110688194
        qz: 0.99899545793631084
      - x: 0.36358621716499329
        y: -1.1339432001113892
        z: -0.0012725458946079016
        qw: -4.5724208985260058e-05
        qx: 0.065776614078804169
        qy: 0.0012211634967937636
        qz: 0.99783066409076238
  -
    -
      - x: 0.36358180642127991
        y: -1.2339431047439575
        z: -0.00090709398500621319
        qw: -7.3552783505285421e-05
        qx: 0.065035859587527098
        qy: 0.0016779171039957958
        qz: 0.99787893308272479
      - x: 0.27310827374458313
        y: -1.2339379787445068
        z: 0.010518796741962433
        qw: 9.0404769461366765e-06
        qx: 0.039413817220276412
        qy: 0.0013730652135282915
        qz: 0.999013957818909
      - x: 0.18197989463806152
        y: -1.2339366674423218
        z: 0.013990683481097221
        qw: 3.8428955553131174e-05
        qx: -0.0018035607347702013
        qy: 0.0010191808622546619
        qz: 0.99973157318448558
      - x: 0.090904369950294495
        y: -1.2339385747909546
        z: 0.0094546936452388763
        qw: 4.3913881309669907e-05
        qx: -0.045427657635168893
        qy: 0.0008144120052566658
        qz: 0.99871948430034241
      - x: 0.00054849381558597088
        y: -1.2339439392089844
        z: -0.0028559498023241758
        qw: 4.3913881309669907e-05
        qx: -0.045427657635168893
        qy: 0.0008144120052566658
        qz: 0.99871948430034241